name: nandocosta
favicon: null
layout_spectrum: 0.6240409999154508
typography_spectrum: 0.07784420414827764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.45447979401797056
  lightness: 0.5113342921249568
  saturation: 0.5140191207174212
  rhythmicContrast: 0.6028672964312136
purpose: []
